// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBno-npjw1mWtdE7viqaen8ozU-YFu4Hj4',
    appId: '1:567807231941:web:8c9fb630e9943a54dbedac',
    messagingSenderId: '567807231941',
    projectId: 'chat-app-19f0b',
    authDomain: 'chat-app-19f0b.firebaseapp.com',
    storageBucket: 'chat-app-19f0b.appspot.com',
    measurementId: 'G-TJYT59BNM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfOSSFn87cxsJjmggwnqKi3NdZoByejVE',
    appId: '1:567807231941:android:8fa23d01c80b46f3dbedac',
    messagingSenderId: '567807231941',
    projectId: 'chat-app-19f0b',
    storageBucket: 'chat-app-19f0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0qjstRPl5TrnRGsDlVB7xbTq35lty1MI',
    appId: '1:567807231941:ios:7dc9c18829da978fdbedac',
    messagingSenderId: '567807231941',
    projectId: 'chat-app-19f0b',
    storageBucket: 'chat-app-19f0b.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0qjstRPl5TrnRGsDlVB7xbTq35lty1MI',
    appId: '1:567807231941:ios:7dc9c18829da978fdbedac',
    messagingSenderId: '567807231941',
    projectId: 'chat-app-19f0b',
    storageBucket: 'chat-app-19f0b.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBno-npjw1mWtdE7viqaen8ozU-YFu4Hj4',
    appId: '1:567807231941:web:4129282d585da4a6dbedac',
    messagingSenderId: '567807231941',
    projectId: 'chat-app-19f0b',
    authDomain: 'chat-app-19f0b.firebaseapp.com',
    storageBucket: 'chat-app-19f0b.appspot.com',
    measurementId: 'G-CKY9ZB0D4T',
  );
}
